apiVersion: v1
kind: Secret
metadata:
  name: {{ include "novigo.fullname" . }}-secrets
  labels:
    {{- include "novigo.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioRootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioRootPassword | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s?schema=public" .Values.postgres.user .Values.secrets.postgresPassword (include "novigo.fullname" .) .Values.postgres.db | quote }}
